# Generated by Django 3.1.7 on 2021-03-17 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='peice',
            new_name='price',
        ),
    ]
